---
- name: make sure needed software is installed
  yum: name=yum-utils
- name: remove old kernel packages for RPM based systems
  shell:  dnf remove -y $(dnf repoquery --installonly --latest-limit=-'{{ ospatch_keep_kernel_nr }}' -q)
...
